{{- if .Values.rabbitmq.provision }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.auth.existingPasswordSecret }}
  labels:
    {{- include "middlemail.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.secretAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  rabbitmq-password: {{ randAlphaNum 10 | b64enc | quote }}
  rabbitmq-erlang-cookie: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
