{{- if .Values.rabbitmq.provision }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.rabbitmq.auth.existingPasswordSecret }}
  labels:
    {{- include "middlemail.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
type: Opaque
data:
  rabbitmq-password: {{ randAlphaNum 10 | b64enc | quote }}
  rabbitmq-erlang-cookie: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
