apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.redis.existingSecret }}
  labels:
    {{- include "middlemail.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.secretAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
data:
  redis-password: {{ randAlphaNum 10 | b64enc | quote }}
